config/routes.rb
Beloc::Application.routes.draw do
resources :beacons
  root 'beacons#index'

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  def index
    @beacon=Beacon.all
  end

  def new
  
  end

  def create
    @beacon=Beacon.new(post_params)
    @beacon.save
    redirect_to @beacon
  end
	
  def show
    @beacon=Beacon.find(params[:id])
  end

 private
  def post_params
    params.require(:beacon).permit(:sid,:loc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/views/beacons/index.html.erb
<h1>Beacons</h1>
</br>
<% @beacon.each do |beacon| %>
<p><%= beacon.sid %></p>
<p><%= beacon.loc %></p>
</br>
<% end %>

app/views/beacons/new.html.erb
<h1>Add Beacon</h1>

<%= form_for :beacon, url: beacons_path do |f| %>
	<p>
		<%= f.label :sid %>
		<%= f.text_field :sid %>	
	</p>

	<p>
		<%= f.label :loc %>
		<%= f.text_field :loc %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/beacons/show.html.erb
<h1>Beacon Details</h1>
<p>
<%= @beacon.sid %>
</p>

<p>
<%= @beacon.loc %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beloc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>